import logging
import re
import os # Added for environment variable access
import nltk # For NLTK data setup
import random # Plagiarism portion ko simulate karne ke liye
import json # For JSON parsing

# --- Gemini API Configuration ---
# IMPORTANT: It is necessary to install the google-generativeai library.
# 'pip install google-generativeai' run karein.
try:
    import google.generativeai as genai
    # Configure your Gemini API key from environment variables for production.
    # On Railway, set a variable named GOOGLE_API_KEY with your actual API key.
    gemini_api_key = os.environ.get("GOOGLE_API_KEY")
    if gemini_api_key:
        genai.configure(api_key=gemini_api_key)
        logging.info("Google Generative AI library loaded and configured for plagiarism_ai_checker_tool.")
        GEMINI_API_AVAILABLE = True
    else:
        logging.warning("GOOGLE_API_KEY environment variable not set. Gemini functions will not work in plagiarism_ai_checker_tool.")
        GEMINI_API_AVAILABLE = False
        # Define a helper message for missing API key if it's not set
        def missing_api_key_error_msg(tool_name):
            return f"Error: Gemini API not configured for {tool_name}. Please ensure GOOGLE_API_KEY environment variable is set."
except ImportError:
    logging.warning("Google Generative AI library not found. Gemini functions will not work in plagiarism_ai_checker_tool.")
    GEMINI_API_AVAILABLE = False
except Exception as e:
    logging.error(f"Error configuring Gemini API for plagiarism_ai_checker_tool: {e}. Gemini functions might not work.")
    GEMINI_API_AVAILABLE = False

# Logging configuration
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- NLTK Data Path Setup ---
# Create directory for NLTK data if it doesn't exist
nltk_data_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'nltk_data')
if not os.path.exists(nltk_data_dir):
    os.makedirs(nltk_data_dir)
    logging.info(f"Created NLTK data directory: {nltk_data_dir}")
nltk.data.path.append(nltk_data_dir)
logging.info(f"NLTK data path added: {nltk_data_dir}")

# --- NLTK Data Download Check ---
def ensure_nltk_data():
    """Ensures necessary NLTK data is downloaded."""
    try:
        nltk.data.find('tokenizers/punkt')
        logging.info("NLTK 'punkt' tokenizer already exists.")
    except nltk.downloader.DownloadError:
        logging.info("Downloading NLTK 'punkt' tokenizer...")
        nltk.download('punkt', download_dir=nltk_data_dir)
        logging.info("NLTK 'punkt' tokenizer downloaded.")
    
    try:
        nltk.data.find('corpora/stopwords')
        logging.info("NLTK 'stopwords' corpus already exists.")
    except nltk.downloader.DownloadError:
        logging.info("Downloading NLTK 'stopwords' corpus...")
        nltk.download('stopwords', download_dir=nltk_data_dir)
        logging.info("NLTK 'stopwords' corpus downloaded.")

# Ensure NLTK data is available when the module starts
ensure_nltk_data()

# --- Gemini Model Helper Function ---
def get_gemini_model():
    """Helper function to get a Gemini model that supports generateContent."""
    if not GEMINI_API_AVAILABLE:
        # Provide specific error message if API is not available due to missing key
        raise Exception("Gemini API is not available. Ensure GOOGLE_API_KEY is set.")
    
    available_models = [m for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
    selected_model_name = None
    for model_info in available_models:
        # Prefer gemini-2.0-flash because it is efficient
        if 'gemini-2.0-flash' in model_info.name:
            selected_model_name = model_info.name
            break
    
    if not selected_model_name:
        if available_models:
            # If flash model is not found, use any available model
            selected_model_name = available_models[0].name
            logging.warning(f"gemini-2.0-flash not found. Using available model: {selected_model_name}")
        else:
            raise Exception("No Gemini model found that supports content generation.")
    
    return genai.GenerativeModel(selected_model_name)

# --- Plagiarism & AI Checker Tool Logic ---
def check_plagiarism_and_ai(text):
    """Checks for AI content using Gemini. (Note: True plagiarism check requires a specialized database comparison tool.)"""
    if not GEMINI_API_AVAILABLE:
        logging.error(missing_api_key_error_msg("plagiarism_ai_checker_tool"))
        return {"is_ai_generated": True, "ai_probability": 0.99, "plagiarism_percentage": 0.0, "suggestions": [missing_api_key_error_msg("plagiarism_ai_checker_tool")]}

    try:
        model = get_gemini_model()
        
        prompt = (
            f"Analyze the following text and estimate the probability that it was generated by an AI. " # Explicitly request English
            f"Provide a percentage score (e.g., '75% AI generated') in English. "
            f"Also, briefly explain your reasoning in English.\n\n"
            f"Do not use any markdown formatting like **bold**, *italic*, or ##headings. Provide plain text.\n\n" # Add formatting instruction
            f"Text to analyze:\n---\n{text}\n---\n\nAnalysis:"
        )
        
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.1, # Keep low for factual analysis
                top_p=0.7,
                top_k=20,
                candidate_count=1,
            )
        )
        
        ai_probability_percent = 0.0
        suggestions = []
        is_ai_generated = False

        if response.candidates and response.candidates[0].content and response.candidates[0].content.parts:
            analysis_text = response.candidates[0].content.parts[0].text.strip()
            
            # Try to extract a percentage
            match = re.search(r'(\d{1,3})%', analysis_text)
            if match:
                ai_probability_percent = float(match.group(1))
            
            ai_probability = ai_probability_percent / 100.0
            is_ai_generated = ai_probability > 0.5
            
            suggestions.append(analysis_text) # Use the full analysis as a suggestion

        if is_ai_generated:
            suggestions.append("This text appears to be AI-generated. To humanize it, try rephrasing sentences, adding personal anecdotes, and varying sentence structure.")
        else:
            suggestions.append("This text appears human-like. No specific suggestions regarding AI detection at this time.")
        
        # Plagiarism portion is still simulated for now, as discussed.
        # A true plagiarism check requires a separate paid API.
        plagiarism_percentage = random.uniform(0.0, 15.0) if random.random() < 0.2 else 0.0
        if plagiarism_percentage > 0:
            suggestions.append(f"Approximately {plagiarism_percentage:.2f}% of the text may contain direct matches to existing sources. Please review carefully.")


        return {
            "is_ai_generated": is_ai_generated,
            "ai_probability": round(ai_probability, 4),
            "plagiarism_percentage": round(plagiarism_percentage, 2), # Simulated for now
            "suggestions": suggestions
        }

    except Exception as e:
        logging.error(f"Error checking AI content with Gemini: {e}", exc_info=True)
        return {"is_ai_generated": True, "ai_probability": 0.99, "plagiarism_percentage": 0.0, "suggestions": [f"Error: AI content detection failed with Gemini. Details: {str(e)}"]}